package Semantic;

public enum CommandType {
    JMP, //(jmp, address, null, null)
    JZ,  //(jz, address, null, null)
    JNZ, //(jnz, address, null, null)
    JE,  //(je, address, null, null)
    JNE, //(jne, address, null, null)
    JG,  //(jg, address, null, null)
    JGE, //(jge, address, null, null)
    JL,  //(jl, address, null, null)
    JLE, //(jle, address, null, null)
    DEF, //(def, name, value, type)
    MOV, //(mov, name, value, null)
    IN,  //(in, null, null, null)
    OUT, //(out, null, null, null)
    ADD, //(add, target, source, source)
    SUB, //(sub, target, source, source)
    INC, //(inc, target, number, null)
    DEC, //(dec, target, number, null)
    MUL, //(mul, target, source, source)
    DIV, //(div, target, source, source)
    MOD, //(div, target, source, source)
    SC,  //(sc, target, null, null)
    PR   //(pr, source, null, null)
}
